In [1]:
import sys
sys.path.append('../../pycroscopy/')
import pycroscopy as px
import numpy as np

//anaconda/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
px.io_utils.check_ssh()

False

In [3]:
px.io_utils.get_time_stamp()

'2018_01_13-20_34_35'

In [4]:
px.io_utils.get_available_memory()/(1024**3)

7.464145660400391

In [5]:
px.io_utils.recommend_cpu_cores(1000, requested_cores=3, lengthy_computation=False)

3

In [6]:
px.io_utils.recommend_cpu_cores(5, requested_cores=3, lengthy_computation=False)

1

In [7]:
px.io_utils.recommend_cpu_cores(5, requested_cores=3, lengthy_computation=True)

3

In [10]:
test = np.random.rand(3) + 1j*(np.random.rand(3))
print(test)
px.io_utils.complex_to_float(test)

[0.89410531+0.86786016j 0.38234165+0.30703404j 0.41421299+0.83045164j]


array([0.89410531, 0.38234165, 0.41421299, 0.86786016, 0.30703404,
       0.83045164])

In [13]:
field_names = ['Amplitude [V]', 'Frequency [Hz]', 'Quality Factor', 'Phase [rad]', 'R2 Criterion']
sho32 = np.dtype({'names': field_names,
                  'formats': [np.float32 for name in field_names]})

test = np.random.rand(3, 5)
print(test)
comp_array = np.zeros(shape=(3), dtype=sho32)
for ind, name in enumerate(field_names):
    comp_array[name] = test[:, ind]
comp_array

[[0.64456319 0.72566938 0.2726904  0.71026383 0.13883276]
 [0.66229234 0.09473536 0.15640059 0.01308547 0.4596285 ]
 [0.31625451 0.77820136 0.20526171 0.83646334 0.87128052]]


array([(0.6445632 , 0.7256694 , 0.2726904 , 0.71026385, 0.13883276),
       (0.66229236, 0.09473536, 0.15640059, 0.01308546, 0.4596285 ),
       (0.3162545 , 0.77820134, 0.2052617 , 0.83646333, 0.8712805 )],
      dtype=[('Amplitude [V]', '<f4'), ('Frequency [Hz]', '<f4'), ('Quality Factor', '<f4'), ('Phase [rad]', '<f4'), ('R2 Criterion', '<f4')])

In [18]:
field_names = ['Amplitude [V]', 'Frequency [Hz]', 'Quality Factor', 'Phase [rad]', 'R2 Criterion']
sho32 = np.dtype({'names': field_names,
                  'formats': [np.float32, np.str, bool, np.complex128, np.uint]})

test = np.random.rand(3, 5)
print(test)
comp_array = np.zeros(shape=(3), dtype=sho32)
for ind, name in enumerate(field_names):
    comp_array[name] = test[:, ind]
comp_array

[[0.87047783 0.92668804 0.55813501 0.77277034 0.16650922]
 [0.26676649 0.98286069 0.48010953 0.97459925 0.31030535]
 [0.05966911 0.79285342 0.83370895 0.63145612 0.29228483]]


array([(0.87047786, '',  True, 0.77277034+0.j, 0),
       (0.2667665 , '',  True, 0.97459925+0.j, 0),
       (0.05966911, '',  True, 0.63145612+0.j, 0)],
      dtype=[('Amplitude [V]', '<f4'), ('Frequency [Hz]', '<U'), ('Quality Factor', '?'), ('Phase [rad]', '<c16'), ('R2 Criterion', '<u8')])

In [29]:
sho32.fields['Amplitude [V]'][0]

dtype('float32')

In [38]:
sho32.fields

mappingproxy({'Amplitude [V]': (dtype('float32'), 0),
              'Frequency [Hz]': (dtype('<U'), 4),
              'Phase [rad]': (dtype('complex128'), 5),
              'Quality Factor': (dtype('bool'), 4),
              'R2 Criterion': (dtype('uint64'), 21)})